import React,{useState,useEffect} from 'react'
import {collection,getDocs} from "firebase/firestore"
import {db} from "../firebase-config"
import {CircularIndeterminate} from '../loadanimation'
import DisplayPost from './DisplayPost'
const Home = () => {
  const [allPost, setAllPost]= useState({});
  const [loading,setLoading] = useState(true);
  const [Search,setSearch] = useState('');
  const [SearchResult,setSearchResult]= useState([])

  const postRef=collection(db,"post")

   useEffect(()=>{
    if(allPost && Search){
      setSearchResult(allPost.filter((item)=>item.user.toLowerCase().includes(Search) || item.prompt.toLowerCase().includes(Search)))
    }
   },[Search])


  useEffect(()=>{
    setLoading(true)
    const getPosts = async()=>{
      await getDocs(postRef)
      .then(data=>{
        setAllPost(data.docs.map(doc=>({...doc.data(),id: doc.id})));
        setLoading(false)

      }
      )
    }
    getPosts()
  },[]) 
  return (
    <div className="container">
      <h1 className="font-extrabold text-[#222328] text-[32px]">My Collection</h1>
      <p className="mt-2 text-[#666e75] text-[14px] max-w-[500px]">Browse through a collection of imaginative and visually stunning images generated by Hugging API</p>
      <div className='generate-form mt-16'>
        <input 
          type="text" 
          name="Search" 
          placeholder="Search your image" 
          onChange={e => setSearch(e.target.value)} 
          value={Search} 
          className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:border-blue-500"
        />
      </div>
      <div className='m-10'>
        {loading ? (
          <div className='flex justify-center items-center'>
            <CircularIndeterminate />
          </div>
        ) : (
          <div className='grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3'>
            {Search && SearchResult ? (
              SearchResult.map(post => <DisplayPost key={post.id} post={post} />)
            ) : (
              allPost.map(post => <DisplayPost key={post.id} post={post} />)
            )}
          </div>
        )}
      </div>
    </div>
  );
};

export default Home